/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TentangRouteImport } from './routes/tentang'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KontakRouteImport } from './routes/kontak'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdukIndexRouteImport } from './routes/produk.index'
import { Route as ArtikelIndexRouteImport } from './routes/artikel.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProdukSlugRouteImport } from './routes/produk.$slug'
import { Route as KategoriSlugRouteImport } from './routes/kategori.$slug'
import { Route as ArtikelSlugRouteImport } from './routes/artikel.$slug'
import { Route as AdminProdukRouteImport } from './routes/admin.produk'
import { Route as AdminPerusahaanRouteImport } from './routes/admin.perusahaan'
import { Route as AdminKontakRouteImport } from './routes/admin.kontak'
import { Route as AdminDownloadRouteImport } from './routes/admin.download'
import { Route as AdminArtikelRouteImport } from './routes/admin.artikel'

const TentangRoute = TentangRouteImport.update({
  id: '/tentang',
  path: '/tentang',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KontakRoute = KontakRouteImport.update({
  id: '/kontak',
  path: '/kontak',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdukIndexRoute = ProdukIndexRouteImport.update({
  id: '/produk/',
  path: '/produk/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtikelIndexRoute = ArtikelIndexRouteImport.update({
  id: '/artikel/',
  path: '/artikel/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProdukSlugRoute = ProdukSlugRouteImport.update({
  id: '/produk/$slug',
  path: '/produk/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const KategoriSlugRoute = KategoriSlugRouteImport.update({
  id: '/kategori/$slug',
  path: '/kategori/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtikelSlugRoute = ArtikelSlugRouteImport.update({
  id: '/artikel/$slug',
  path: '/artikel/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProdukRoute = AdminProdukRouteImport.update({
  id: '/produk',
  path: '/produk',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPerusahaanRoute = AdminPerusahaanRouteImport.update({
  id: '/perusahaan',
  path: '/perusahaan',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKontakRoute = AdminKontakRouteImport.update({
  id: '/kontak',
  path: '/kontak',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDownloadRoute = AdminDownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArtikelRoute = AdminArtikelRouteImport.update({
  id: '/artikel',
  path: '/artikel',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/download': typeof DownloadRoute
  '/kontak': typeof KontakRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tentang': typeof TentangRoute
  '/admin/artikel': typeof AdminArtikelRoute
  '/admin/download': typeof AdminDownloadRoute
  '/admin/kontak': typeof AdminKontakRoute
  '/admin/perusahaan': typeof AdminPerusahaanRoute
  '/admin/produk': typeof AdminProdukRoute
  '/artikel/$slug': typeof ArtikelSlugRoute
  '/kategori/$slug': typeof KategoriSlugRoute
  '/produk/$slug': typeof ProdukSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/artikel/': typeof ArtikelIndexRoute
  '/produk/': typeof ProdukIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/download': typeof DownloadRoute
  '/kontak': typeof KontakRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tentang': typeof TentangRoute
  '/admin/artikel': typeof AdminArtikelRoute
  '/admin/download': typeof AdminDownloadRoute
  '/admin/kontak': typeof AdminKontakRoute
  '/admin/perusahaan': typeof AdminPerusahaanRoute
  '/admin/produk': typeof AdminProdukRoute
  '/artikel/$slug': typeof ArtikelSlugRoute
  '/kategori/$slug': typeof KategoriSlugRoute
  '/produk/$slug': typeof ProdukSlugRoute
  '/admin': typeof AdminIndexRoute
  '/artikel': typeof ArtikelIndexRoute
  '/produk': typeof ProdukIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/download': typeof DownloadRoute
  '/kontak': typeof KontakRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tentang': typeof TentangRoute
  '/admin/artikel': typeof AdminArtikelRoute
  '/admin/download': typeof AdminDownloadRoute
  '/admin/kontak': typeof AdminKontakRoute
  '/admin/perusahaan': typeof AdminPerusahaanRoute
  '/admin/produk': typeof AdminProdukRoute
  '/artikel/$slug': typeof ArtikelSlugRoute
  '/kategori/$slug': typeof KategoriSlugRoute
  '/produk/$slug': typeof ProdukSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/artikel/': typeof ArtikelIndexRoute
  '/produk/': typeof ProdukIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/download'
    | '/kontak'
    | '/login'
    | '/sitemap.xml'
    | '/tentang'
    | '/admin/artikel'
    | '/admin/download'
    | '/admin/kontak'
    | '/admin/perusahaan'
    | '/admin/produk'
    | '/artikel/$slug'
    | '/kategori/$slug'
    | '/produk/$slug'
    | '/admin/'
    | '/artikel/'
    | '/produk/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/download'
    | '/kontak'
    | '/login'
    | '/sitemap.xml'
    | '/tentang'
    | '/admin/artikel'
    | '/admin/download'
    | '/admin/kontak'
    | '/admin/perusahaan'
    | '/admin/produk'
    | '/artikel/$slug'
    | '/kategori/$slug'
    | '/produk/$slug'
    | '/admin'
    | '/artikel'
    | '/produk'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/download'
    | '/kontak'
    | '/login'
    | '/sitemap.xml'
    | '/tentang'
    | '/admin/artikel'
    | '/admin/download'
    | '/admin/kontak'
    | '/admin/perusahaan'
    | '/admin/produk'
    | '/artikel/$slug'
    | '/kategori/$slug'
    | '/produk/$slug'
    | '/admin/'
    | '/artikel/'
    | '/produk/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DownloadRoute: typeof DownloadRoute
  KontakRoute: typeof KontakRoute
  LoginRoute: typeof LoginRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TentangRoute: typeof TentangRoute
  ArtikelSlugRoute: typeof ArtikelSlugRoute
  KategoriSlugRoute: typeof KategoriSlugRoute
  ProdukSlugRoute: typeof ProdukSlugRoute
  ArtikelIndexRoute: typeof ArtikelIndexRoute
  ProdukIndexRoute: typeof ProdukIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tentang': {
      id: '/tentang'
      path: '/tentang'
      fullPath: '/tentang'
      preLoaderRoute: typeof TentangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontak': {
      id: '/kontak'
      path: '/kontak'
      fullPath: '/kontak'
      preLoaderRoute: typeof KontakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produk/': {
      id: '/produk/'
      path: '/produk'
      fullPath: '/produk/'
      preLoaderRoute: typeof ProdukIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artikel/': {
      id: '/artikel/'
      path: '/artikel'
      fullPath: '/artikel/'
      preLoaderRoute: typeof ArtikelIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/produk/$slug': {
      id: '/produk/$slug'
      path: '/produk/$slug'
      fullPath: '/produk/$slug'
      preLoaderRoute: typeof ProdukSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kategori/$slug': {
      id: '/kategori/$slug'
      path: '/kategori/$slug'
      fullPath: '/kategori/$slug'
      preLoaderRoute: typeof KategoriSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artikel/$slug': {
      id: '/artikel/$slug'
      path: '/artikel/$slug'
      fullPath: '/artikel/$slug'
      preLoaderRoute: typeof ArtikelSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/produk': {
      id: '/admin/produk'
      path: '/produk'
      fullPath: '/admin/produk'
      preLoaderRoute: typeof AdminProdukRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/perusahaan': {
      id: '/admin/perusahaan'
      path: '/perusahaan'
      fullPath: '/admin/perusahaan'
      preLoaderRoute: typeof AdminPerusahaanRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kontak': {
      id: '/admin/kontak'
      path: '/kontak'
      fullPath: '/admin/kontak'
      preLoaderRoute: typeof AdminKontakRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/download': {
      id: '/admin/download'
      path: '/download'
      fullPath: '/admin/download'
      preLoaderRoute: typeof AdminDownloadRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/artikel': {
      id: '/admin/artikel'
      path: '/artikel'
      fullPath: '/admin/artikel'
      preLoaderRoute: typeof AdminArtikelRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminArtikelRoute: typeof AdminArtikelRoute
  AdminDownloadRoute: typeof AdminDownloadRoute
  AdminKontakRoute: typeof AdminKontakRoute
  AdminPerusahaanRoute: typeof AdminPerusahaanRoute
  AdminProdukRoute: typeof AdminProdukRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminArtikelRoute: AdminArtikelRoute,
  AdminDownloadRoute: AdminDownloadRoute,
  AdminKontakRoute: AdminKontakRoute,
  AdminPerusahaanRoute: AdminPerusahaanRoute,
  AdminProdukRoute: AdminProdukRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DownloadRoute: DownloadRoute,
  KontakRoute: KontakRoute,
  LoginRoute: LoginRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TentangRoute: TentangRoute,
  ArtikelSlugRoute: ArtikelSlugRoute,
  KategoriSlugRoute: KategoriSlugRoute,
  ProdukSlugRoute: ProdukSlugRoute,
  ArtikelIndexRoute: ArtikelIndexRoute,
  ProdukIndexRoute: ProdukIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
